### ISSUE TITLE
multiple values encoding/decoding

### ISSUE THREAD

**Issue by verrchu** [gklijs/schema_registry_converter#60] opened 2021-08-24 14:59 UTC
At times it is convenient to pass multiple events at once to avoid inconsistet state if for example 1 out of 10 events causes some kind of error on its way.

I guess it would be great to have some API llike (encode|decode)_many which would pack events together and then unpack then successfully. avro-rs works this way actually.

**Comment by gklijs** [comment] 2021-08-24 16:56
Hi, thanks for creating the issue. I do need a little bit more context through. What would de difference from running it 10 times and just ignoring the error?

**Comment by verrchu** [comment] 2021-08-25 05:15
The idea is to be able to send events in batches. Tsis way eitger all the events are sent or fail to send. This allows for better consistency in cases when for example one API request results in multiple events.

**Comment by gklijs** [comment] 2021-08-25 10:46
Yes, but this library don't send the events. Therefore I still don't know how the api would look. You could already try to encode|decode multiple items, and only send/use them when they all succeed.

**Comment by verrchu** [comment] 2021-08-25 12:07
Ok maybe I am not being clear enough.

I am suggesting that this library provides the following API
`
encode_many(schema, values) -> encoded
decode_many(encoded) -> values
`

this way an application can encode many events in one blob
and then atomically send this blob over the wire

**Comment by gklijs** [comment] 2021-08-25 14:15
Yes, I get that, and with avro you might need/want to reuse schema's. But in this case there already is a cache for the information needed from the schema registry. So I don't see the added value of adding something like that to this crate. I also don't really understand how you would like to send everything in one blob, since each blob should be properly coded.

**Comment by gklijs** [comment] 2021-09-11 05:43
Could you please once more try to explain how this is useful, and what would be the advantage of having it in the library? I'm stil failing to see why you couldn't batch them on you side, since the schema information is cashed anyway.

**Comment by verrchu** [comment] 2021-09-11 06:41
Let me try to emphasize the problem once more.

There is a typical web app which opens a DB transaction in the beginning of request handling and commits the transaction in the end if all goes well.

In the process of request handling it might accumulate more then one event to send afterwards.

The strategy of event transfer in this app is to send the event(s) right before commiting the transaction so that we know that sent events represent consistent state.

The problem with this approach i that when having multiple events to send the application could fail somewhere in the middle and only some events are succesfully sent while the transaction gets rollbacked.

The solution i see is to serialize those events into single blob and send them at once and deserialize this blb into separate events on the other end (avro-ra does similar thing).

Unfortunately i can't see how the "batching" you mentioned can be done otherwise.

**Comment by gklijs** [comment] 2021-09-11 11:52
The problem is that this library is only concerned with getting the messages in the correct binary format. You could for example create 5 messages, one after the other using this library, before sending them to a broker.

But Kafka doesn't has the concept of transactions, so even if you send all 5 right after another to Kafka, it might be that some fail, and some succeed. Although with the correct settings you can be almost sure they would always be send in the same batch, so they do will either fail or succeed all.

An alternative approach would be to is a relational DB and put all the messages there in a transaction, optionally using the outbox pattern. Then using Debezium to get them from the database to Kafka.

I'm closing this issue, since it's a problem this library can't fix.

**Closed by gklijs** 2021-09-11 11:52 UTC
