### ISSUE TITLE
working with avro decimal type

### ISSUE THREAD

**Issue by sfsf9797** [gklijs/schema_registry_converter#113] opened 2024-09-06 08:27 UTC
<img width="374" alt="image" src="https://github.com/user-attachments/assets/37155ee5-3aab-439f-b8e9-db6897154562">

Since this crate use apache avro [to_value] (https://github.com/gklijs/schema_registry_converter/blob/main/src/avro_common.rs#L144) function to convert serializable item to `Value` type, it might not work with avro schema with decimal field as the avro [serializer](https://github.com/apache/avro/blob/main/lang/rust/avro/src/ser.rs#L109) might not convert it properly.

```
use apache_avro::Decimal;

#[derive(Serialize, Clone, Debug)]
pub struct item {
    // indexes
    pub total_successful_transaction_blocks: Decimal,
```

The total_successful_transaction_blocks will be serialized to
`
"total_successful_transaction_blocks", Record([("value", Array([Int(1), Array([Int(7)])])), ("len", Long(1))]))`

**Comment by martin-g** [comment] 2024-09-09 10:52
The issue is not very clear to me...
Is there something that should be fixed/improved in the apache_avro crate or it is an issue only in schema_registry_converter ?

**Comment by gklijs** [comment] 2024-10-13 13:29
Clsoing this, as it was fixed by https://github.com/gklijs/schema_registry_converter/pull/114

**Closed by gklijs** 2024-10-13 13:29 UTC
